steps:
  # Run the Maven build
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/organization:tag1','-t', 'gcr.io/$PROJECT_ID/organization:latest', '.']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
     - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
     - 'CLOUDSDK_CONTAINER_CLUSTER=myk8scluster'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set','image','deployment','organization', 'organization=gcr.io/$PROJECT_ID/organization:latest']
    env:
     - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
     - 'CLOUDSDK_CONTAINER_CLUSTER=myk8scluster'   
images: ['gcr.io/$PROJECT_ID/organization:tag1','gcr.io/$PROJECT_ID/organization:latest']